const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
const LOGOUT_FAILED = 'LOGOUT_FAILED'

const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAILED = 'UPDATE_FAILED'
export const USER_PROFILE = 'USER_PROFILE'
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED'
export const USER_PROFILE_DATA = 'USER_PROFILE_DATA'
export { LOGOUT_FAILED, LOGOUT_SUCCESS, LOGIN_SUCCESS }
