export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'

export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'

export const ASSIGN_USERS_TO_MANAGERS_START = 'ASSIGN_USERS_TO_MANAGERS_START'
export const ASSIGN_USERS_TO_MANAGERS_SUCCESS =
  'ASSIGN_USERS_TO_MANAGERS_SUCCESS'
export const ASSIGN_USERS_TO_MANAGERS_FAIL = 'ASSIGN_USERS_TO_MANAGERS_FAIL'
